parameters:

services:
    _defaults:
        autowire: true      
        autoconfigure: true 
        bind:
            $apiKey: '%env(FOOTBALL_API_KEY)%'
    App\:
        resource: '../src/'
    
    App\DataCollector\FootballApiCollector:
        tags:
            - { name: 'data_collector', template: 'data_collector/football_api.html.twig', id: 'football_api' }
    

